### ISSUE TITLE
Discovery timeout when "showGroups": true

### ISSUE THREAD

**Issue by dmckillican** [rainlake/homebridge-platform-lightify#7]
Hi rainlake

Thank you so much for for adding groups to your code. I'm excited about getting this working.

I have set the "showGroups": true, "hideNodes": true as below:

{
"platform": "Lightify",
"bridge_ip": "192.168.0.3",
"name": "Lightify",
"showGroups": true,
"hideNodes": true
}

Doing this stops home bridge from launching and I notice that I get a statement saying "[Lightify] Discovered failed timeout"

I have attached the debug code below

perhaps I simply have the wrong config? I removed the showGroups setting which launched homebridge with the hideNodes: true working. It was only showGrops that caused the issue.

Any ideas?

thank you again!

Homes-Mac-mini:~ homeauto$ homebridge -D
[3/16/2017, 7:16:10 PM] Loaded plugin: homebridge-camera-ffmpeg
[3/16/2017, 7:16:10 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[3/16/2017, 7:16:10 PM] ---
[3/16/2017, 7:16:10 PM] Loaded plugin: homebridge-efergy
[3/16/2017, 7:16:10 PM] Registering accessory 'homebridge-efergy.Efergy'
[3/16/2017, 7:16:10 PM] ---
[3/16/2017, 7:16:10 PM] Loaded plugin: homebridge-homeassistant
[3/16/2017, 7:16:10 PM] Registering platform 'homebridge-homeassistant.HomeAssistant'
[3/16/2017, 7:16:10 PM] ---
[3/16/2017, 7:16:10 PM] Loaded plugin: homebridge-ip-camera
[3/16/2017, 7:16:10 PM] Registering platform 'homebridge-ip-camera.Camera-IP'
[3/16/2017, 7:16:10 PM] ---
[3/16/2017, 7:16:10 PM] Loaded plugin: homebridge-platform-lightify
[3/16/2017, 7:16:10 PM] Registering platform 'homebridge-platform-lightify.Lightify'
[3/16/2017, 7:16:10 PM] ---
[3/16/2017, 7:16:11 PM] Loaded plugin: homebridge-platform-orvibo
[3/16/2017, 7:16:11 PM] Registering platform 'homebridge-platform-orvibo.Orvibo'
[3/16/2017, 7:16:11 PM] ---
[3/16/2017, 7:16:11 PM] Loaded plugin: homebridge-platform-wemo
[3/16/2017, 7:16:11 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[3/16/2017, 7:16:11 PM] ---
[3/16/2017, 7:16:11 PM] Loaded plugin: homebridge-server
[3/16/2017, 7:16:11 PM] Registering platform 'homebridge-server.Server'
[3/16/2017, 7:16:11 PM] ---
[3/16/2017, 7:16:11 PM] Loaded config.json with 1 accessories and 4 platforms.
[3/16/2017, 7:16:11 PM] ---
[3/16/2017, 7:16:11 PM] Loading 4 platforms...
[3/16/2017, 7:16:11 PM] Initializing Orvibo platform...
[3/16/2017, 7:16:11 PM] [Lightify] Initializing Lightify platform...
[3/16/2017, 7:16:11 PM] [WeMo Platform] Initializing BelkinWeMo platform...
[3/16/2017, 7:16:11 PM] Initializing Camera-IP platform...
[3/16/2017, 7:16:11 PM] Loading 1 accessories...
[3/16/2017, 7:16:11 PM] [Efergy] Initializing Efergy accessory...
Load homebridge-camera-ffmpeg.Camera-ffmpeg
[3/16/2017, 7:16:11 PM] GardenCam is running on port 56393.
[3/16/2017, 7:16:11 PM] [Lightify] Connected to Lightify Bridge
[3/16/2017, 7:16:11 PM] [Lightify] command sent [1][070000130100000001]
[3/16/2017, 7:16:11 PM] [Lightify] socket data: [6f08011301000000002b004310af9d010000261884020102040702080000648e0a010000ff426564203100000000000000000000000000000000000000ad68108b010000261884020102040702200001648e0a010000ff4775657374203300000000000000000000000000000000000b2e8289010000261884020102040702200001648e0a010000ff47756573742032000000000000000000000000000000000064a4c2b2010000261884020102040702200001648e0a010000ff477565737420310000000000000000000000000000000000e7426b9e010000261884020102040002000001648e0a010000ff4775657374204c20320000000000000000000000000000000ca4438b010000261884020102040002400000648e0a990000ff4f666669636520446f6f7200000000000000000000000000dea6638e010000261884020102040702080000648e0a010000ff426564203200000000000000000000000000000000000000a1acc3d7d90000261884020102049202800000328e0a010000ff4c61756e647279204c616d70000000000000000000000000d07e449b010000261884020102040702010201648e0a010000ff4c6f756e676520536f6661203100000000000000000000001aa3068f010000261884020102040002010201648e0a010000ff4c6f756e67652043656e7472652031000000000000000000a240419d010000261884020102040002010201648e0a010000ff4c6f756e6765204d616e74656c20320000000000000000001ad1b289010000261884020102040702010201648e0a010000ff4c6f756e6765204d616e74656c20310000000000000000003a11168e010000261884020102040002400000648e0a010000ff4f6666696365204465736b20520000000000000000000000bffcf9b2010000261884020102040002000000648e0a010000ff43696e656d61203200000000000000000000000000000000a849ba76cb00002618840a010204010220000014ac0affffffff4775657374204c616d70000000000000000000000000000074fec69c010000261884020102040002020000648e0a010000ff42616c636f6e792042656400000000000000000000000000ea58de57000000261884020102040002020000648e0a010000ff42616c636f6e79205461626c6500000000000000000000008ae02eb6010000261884020102040002020000648e0a010000ff42616c636f6e792042425100000000000000000000000000536b6fd4ca00002618840a0102040102100000648e0affffffff456e7472616e636500000000000000000000000000000000df706689010000261884020102040002100000648e0a010000ff48616c6c2042656420446f6f720000000000000000000000d6a25a8e010000261884020102040002100000648e0a010000ff48616c6c20446f6f7200000000000000000000000000000094015889010000261884020102040002080000648e0a010000ff42656420446f6f720000000000000000000000000000000023cae4af010000261884020102040002400000648e0a990000ff4f6666696365205069616e6f0000000000000000000000004845cbb1010000261884020102040702080000648e0a010000ff42656420436c6f7365740000000000000100000000000000ffffee9c010000261884000102040700000101648e0a010000ff47617264656e2050616c6d2031000000030000000000000065083e9b010000261884020102040702080000648e0a010000ff426564204d6972726f7200000000000000000000000000008264ff8e010000261884020102040702010201648e0a010000ff4c6f756e676520536f66612032000000000000000000000054f8128a010000261884020102040702010201648e0a010000ff4c6f756e67652043656e747261]
[3/16/2017, 7:16:11 PM] [Lightify] Expected len [2161]
[3/16/2017, 7:16:11 PM] [Lightify] len = [1400]
[3/16/2017, 7:16:11 PM] [WeMo Platform] Online: Front Garden Irrigation [94103E32C180]
[3/16/2017, 7:16:11 PM] [Lightify] socket data: [6c00000000000000000000b754b07cc90000261884020102049202040200648e0a010000ff4b69746368656e2042656e63682031000000000000000000c7dcd0130100002618840a0102040102080000648e0affffffff426564204c616d70000000000000000000000000000000007f52938a010000261884020102040002040200648e0a010000ff4b69746368656e2052000000000000000000000000000000754ba48e010000261884020102040002400000648e0a010000ff4f6666696365204465736b204c0000000000000000000000ca57478b010000261884020102040000000000648e0a010000ff43696e656d612031000000000000000000000000000000000d04add3d90000261884020102040702040200648e0a010000ff4b69746368656e2042656e636820320000000000000000002b86008f010000261884020102040002040200648e0a010000ff4b69746368656e204c0000000000000000000000000000009616b890010000261884020102040002000001648e0a010000ff4775657374204c20310000000000000000000000000000002782668b010000261884020102040002000000648e0a010000ff43696e656d61203300000000000000000000000000000000d136c79c010000261884020102040002000000648e0a010000ff43696e656d612034000000000000000000000000000000001e0416b4010000261884020102040702000101648e0a010000ff4465636b204c6f756e67650000000000010000000000000008075d9e010000261884020102040702000101648e0a010000ff47617264656e2050616c6d00000000000000000000000000ffff068b010000261884000102040700000101648e0a010000ff4465636b20446f6f720000000000000003000000000000006a35449d0100002618840201020400020000001c8e0a010000ff46726f6e7420446f6f720000000000000000000000000000b6fc0791010000261884020102040702000000648e0a010000ff47617264656e2043617220506f7274000000000000000000]
[3/16/2017, 7:16:11 PM] [Lightify] Expected len [2161]
[3/16/2017, 7:16:11 PM] [Lightify] len = [2161]
[3/16/2017, 7:16:11 PM] [Lightify] got response for seq [1][6f08011301000000002b004310af9d010000261884020102040702080000648e0a010000ff426564203100000000000000000000000000000000000000ad68108b010000261884020102040702200001648e0a010000ff4775657374203300000000000000000000000000000000000b2e8289010000261884020102040702200001648e0a010000ff47756573742032000000000000000000000000000000000064a4c2b2010000261884020102040702200001648e0a010000ff477565737420310000000000000000000000000000000000e7426b9e010000261884020102040002000001648e0a010000ff4775657374204c20320000000000000000000000000000000ca4438b010000261884020102040002400000648e0a990000ff4f666669636520446f6f7200000000000000000000000000dea6638e010000261884020102040702080000648e0a010000ff426564203200000000000000000000000000000000000000a1acc3d7d90000261884020102049202800000328e0a010000ff4c61756e647279204c616d70000000000000000000000000d07e449b010000261884020102040702010201648e0a010000ff4c6f756e676520536f6661203100000000000000000000001aa3068f010000261884020102040002010201648e0a010000ff4c6f756e67652043656e7472652031000000000000000000a240419d010000261884020102040002010201648e0a010000ff4c6f756e6765204d616e74656c20320000000000000000001ad1b289010000261884020102040702010201648e0a010000ff4c6f756e6765204d616e74656c20310000000000000000003a11168e010000261884020102040002400000648e0a010000ff4f6666696365204465736b20520000000000000000000000bffcf9b2010000261884020102040002000000648e0a010000ff43696e656d61203200000000000000000000000000000000a849ba76cb00002618840a010204010220000014ac0affffffff4775657374204c616d70000000000000000000000000000074fec69c010000261884020102040002020000648e0a010000ff42616c636f6e792042656400000000000000000000000000ea58de57000000261884020102040002020000648e0a010000ff42616c636f6e79205461626c6500000000000000000000008ae02eb6010000261884020102040002020000648e0a010000ff42616c636f6e792042425100000000000000000000000000536b6fd4ca00002618840a0102040102100000648e0affffffff456e7472616e636500000000000000000000000000000000df706689010000261884020102040002100000648e0a010000ff48616c6c2042656420446f6f720000000000000000000000d6a25a8e010000261884020102040002100000648e0a010000ff48616c6c20446f6f7200000000000000000000000000000094015889010000261884020102040002080000648e0a010000ff42656420446f6f720000000000000000000000000000000023cae4af010000261884020102040002400000648e0a990000ff4f6666696365205069616e6f0000000000000000000000004845cbb1010000261884020102040702080000648e0a010000ff42656420436c6f7365740000000000000100000000000000ffffee9c010000261884000102040700000101648e0a010000ff47617264656e2050616c6d2031000000030000000000000065083e9b010000261884020102040702080000648e0a010000ff426564204d6972726f7200000000000000000000000000008264ff8e010000261884020102040702010201648e0a010000ff4c6f756e676520536f66612032000000000000000000000054f8128a010000261884020102040702010201648e0a010000ff4c6f756e67652043656e7472616c00000000000000000000b754b07cc90000261884020102049202040200648e0a010000ff4b69746368656e2042656e63682031000000000000000000c7dcd0130100002618840a0102040102080000648e0affffffff426564204c616d70000000000000000000000000000000007f52938a010000261884020102040002040200648e0a010000ff4b69746368656e2052000000000000000000000000000000754ba48e010000261884020102040002400000648e0a010000ff4f6666696365204465736b204c0000000000000000000000ca57478b010000261884020102040000000000648e0a010000ff43696e656d612031000000000000000000000000000000000d04add3d90000261884020102040702040200648e0a010000ff4b69746368656e2042656e636820320000000000000000002b86008f010000261884020102040002040200648e0a010000ff4b69746368656e204c0000000000000000000000000000009616b890010000261884020102040002000001648e0a010000ff4775657374204c20310000000000000000000000000000002782668b010000261884020102040002000000648e0a010000ff43696e656d61203300000000000000000000000000000000d136c79c010000261884020102040002000000648e0a010000ff43696e656d612034000000000000000000000000000000001e0416b4010000261884020102040702000101648e0a010000ff4465636b204c6f756e67650000000000010000000000000008075d9e010000261884020102040702000101648e0a010000ff47617264656e2050616c6d00000000000000000000000000ffff068b010000261884000102040700000101648e0a010000ff4465636b20446f6f720000000000000003000000000000006a35449d0100002618840201020400020000001c8e0a010000ff46726f6e7420446f6f720000000000000000000000000000b6fc0791010000261884020102040702000000648e0a010000ff47617264656e2043617220506f7274000000000000000000]
[3/16/2017, 7:16:11 PM] [Lightify] found request
[3/16/2017, 7:16:11 PM] [Lightify] command sent [2][0700021e0200000000]
[3/16/2017, 7:16:11 PM] [WeMo Platform] Online: Lawn Irrigation [94103E32EDDC]
[3/16/2017, 7:16:11 PM] [Lightify] socket data: [bd00031e02000000000a0001004c6f756e676500000000000000000000020042616c636f6e7900000000000000000003004b69746368656e0000000000000000000400426564726f6f6d000000000000000000050048616c6c0000000000000000000000000600477565737420526f6f6d00000000000007004f66666963650000000000000000000008004c61756e647279000000000000000000090047617264656e000000000000000000000a004c6976696e6720526f6f6d0000000000]
[3/16/2017, 7:16:11 PM] [Lightify] Expected len [191]
[3/16/2017, 7:16:11 PM] [Lightify] len = [191]
[3/16/2017, 7:16:11 PM] [Lightify] got response for seq [2][bd00031e02000000000a0001004c6f756e676500000000000000000000020042616c636f6e7900000000000000000003004b69746368656e0000000000000000000400426564726f6f6d000000000000000000050048616c6c0000000000000000000000000600477565737420526f6f6d00000000000007004f66666963650000000000000000000008004c61756e647279000000000000000000090047617264656e000000000000000000000a004c6976696e6720526f6f6d0000000000]
[3/16/2017, 7:16:11 PM] [Lightify] found request
[3/16/2017, 7:16:11 PM] [Lightify] command sent [3][08000226030000000100]
[3/16/2017, 7:16:11 PM] [Lightify] command sent [4][08000226040000000200]
[3/16/2017, 7:16:11 PM] [Lightify] command sent [5][08000226050000000300]
[3/16/2017, 7:16:11 PM] [Lightify] command sent [6][08000226060000000400]
[3/16/2017, 7:16:11 PM] [Lightify] command sent [7][08000226070000000500]
[3/16/2017, 7:16:11 PM] [Lightify] command sent [8][08000226080000000600]
[3/16/2017, 7:16:11 PM] [Lightify] command sent [9][08000226090000000700]
[3/16/2017, 7:16:11 PM] [Lightify] command sent [10][080002260a0000000800]
[3/16/2017, 7:16:11 PM] [Lightify] command sent [11][080002260b0000000900]
[3/16/2017, 7:16:11 PM] [Lightify] command sent [12][080002260c0000000a00]
[3/16/2017, 7:16:11 PM] [Lightify] socket data: [4a000326030000000001004c6f756e67650000000000000000000006449b010000261884068f010000261884419d010000261884b289010000261884ff8e010000261884128a010000261884]
[3/16/2017, 7:16:11 PM] [Lightify] Expected len [76]
[3/16/2017, 7:16:11 PM] [Lightify] len = [76]
[3/16/2017, 7:16:11 PM] [Lightify] got response for seq [3][4a000326030000000001004c6f756e67650000000000000000000006449b010000261884068f010000261884419d010000261884b289010000261884ff8e010000261884128a010000261884]
[3/16/2017, 7:16:11 PM] [Lightify] found request
[3/16/2017, 7:16:12 PM] [Lightify] send command timeout [4][08000226040000000200]
[3/16/2017, 7:16:12 PM] [Lightify] send command timeout [5][08000226050000000300]
[3/16/2017, 7:16:12 PM] [Lightify] send command timeout [6][08000226060000000400]
[3/16/2017, 7:16:12 PM] [Lightify] send command timeout [7][08000226070000000500]
[3/16/2017, 7:16:12 PM] [Lightify] Discovered failed timeout
[3/16/2017, 7:16:12 PM] [Lightify] send command timeout [8][08000226080000000600]
[3/16/2017, 7:16:12 PM] [Lightify] send command timeout [9][08000226090000000700]
[3/16/2017, 7:16:12 PM] [Lightify] send command timeout [10][080002260a0000000800]
[3/16/2017, 7:16:12 PM] [Lightify] send command timeout [11][080002260b0000000900]
[3/16/2017, 7:16:12 PM] [Lightify] send command timeout [12][080002260c0000000a00]
[3/16/2017, 7:16:16 PM] New Orvibo found: Socket [accf2348f2f6]
[3/16/2017, 7:16:16 PM] New Orvibo found: Socket [accf2348ef44]
[3/16/2017, 7:16:17 PM] Subscription to accf2348ef44 successful!
[3/16/2017, 7:16:17 PM] Subscription to accf2348f2f6 successful!
[3/16/2017, 7:16:18 PM] A device has been queried. Name (if set): Garden
[3/16/2017, 7:16:18 PM] Orvibo Online: Garden [accf2348ef44]
[3/16/2017, 7:16:18 PM] Configuring: Garden
[3/16/2017, 7:16:18 PM] A device has been queried. Name (if set): Pond Pump
[3/16/2017, 7:16:18 PM] Orvibo Online: Pond Pump [accf2348f2f6]
[3/16/2017, 7:16:18 PM] Configuring: Pond Pump

**Comment by rainlake** [comment]
Hi, disable group for now.
Lightify gateway does not take multiple commands at a time, I have to
change something to make it work

**Comment by rainlake** [comment]
Hi, dmckillican
I've fixed this issue. I also discovered lightify might send wrong response for new created groups. they might changed their protocol or something. I've also put some changes to avoid this.
I will push my changes after testing.
Thanks!

**Comment by dmckillican** [comment]
Hi Rainlake,

Thank you again. I am still having the same issue, but I notice that when I update the plugin it is still pulling 0.2.6? perhaps its just a publishing error and I don't have the latest code?

Thanks!! I'm very grateful for your kind efforts.

**Comment by dmckillican** [comment]
Hi again,

I completely removed the plugin and re-installed it. It is still pulling version 0.2.6 and the package.json file says:

 ],
  "_from": "homebridge-platform-lightify@latest",
  "_id": "homebridge-platform-lightify@0.2.6",
  "_inCache": true,
  "_location": "/homebridge-platform-lightify",
  "_nodeVersion": "5.6.0",
  "_npmOperationalInternal": {
    "host": "packages-12-west.internal.npmjs.com",
    "tmp": "tmp/homebridge-platform-lightify-0.2.6.tgz_1489290714390_0.15616435557603836"
  },

I presume it's just a repository error?

**Comment by dmckillican** [comment]
I managed to get the right version by downloading and installing locally, but now get the following error. I hope this isn't putting you out of your way!

[3/18/2017, 8:33:58 AM] [Lightify] Expected len [52]
[3/18/2017, 8:33:58 AM] [Lightify] len = [52]
[3/18/2017, 8:33:58 AM] [Lightify] got response for seq [4][320003260400000000020042616c636f6e7900000000000000000003c69c010000261884de570000002618842eb6010000261884]
[3/18/2017, 8:33:58 AM] [Lightify] found request
[3/18/2017, 8:33:58 AM] [Lightify] command sent [5][08000226050000000300]
[3/18/2017, 8:33:59 AM] [Lightify] socket data: [3a000326050000000003004b69746368656e00000000000000000004b07cc90000261884938a010000261884add3d90000261884008f010000261884]
[3/18/2017, 8:33:59 AM] [Lightify] Expected len [60]
[3/18/2017, 8:33:59 AM] [Lightify] len = [60]
[3/18/2017, 8:33:59 AM] [Lightify] got response for seq [5][3a000326050000000003004b69746368656e00000000000000000004b07cc90000261884938a010000261884add3d90000261884008f010000261884]
[3/18/2017, 8:33:59 AM] [Lightify] found request
/usr/local/bin/node[28539]: ../src/node_buffer.cc:739:void node::Buffer::ReadFloatGeneric(const FunctionCallbackInfo<v8::Value> &) [T = double, endianness = node::Endianness::kLittleEndian]: Assertion `(offset + sizeof(T)) <= (ts_obj_length)' failed.
 1: node::Abort() [/usr/local/bin/node]
 2: node::RunMicrotasks(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 3: void node::Buffer::ReadFloatGeneric<double, (node::Endianness)1>(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/local/bin/node]
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x3d509cd063a7
Abort trap: 6
Homes-Mac-mini:~ homeauto$

**Comment by dmckillican** [comment]
Sorry, I made some comments (which I have deleted) because I missed that you were still testing. Thank you as always. I owe you a beer

**Comment by rainlake** [comment]
Hi, I pushed to github but did not publish to npm, I need few more hours to
test before publish
The error you saw I have fixed. You have to change package.json to correct
version. That will also be published soon.
Thank you.

**Comment by dmckillican** [comment]
Great. thank you. You should contact Osram and tell them how to do it properly!

**Comment by rainlake** [comment]
I have published all changes to npm. your issue should have been fixed.
FYI:  group only show as 'on'  if all lights in group is on. this might be different from lightify app.
let me know if you want something else.
Thanks!

**Comment by dmckillican** [comment]
This awesome thank you. I will try it immediately

**Comment by dmckillican** [comment]
Installed and working awesomely! thank you - question, can I dim? They're showing as on/off switches. Amazing work Rainlake!

**Comment by rainlake** [comment]
No. You may create a new feature request :)

**Comment by dmckillican** [comment]
This is so so much better! I'm also using homebridge-alexa, and it now works amazingly! (I was waiting up to 10 minutes for the official Osram Alexa skill to respond).

**Comment by dmckillican** [comment]
I feel so demanding!

**Comment by rainlake** [comment]
I did not know there is a homebridge-alexa,will try it tomorrow.

**Comment by dmckillican** [comment]
Its new - along side your lightify plugin it works perfectly. The Alexa OSram skill was really poor, but now Alexa can trigger your plugin immediately. It's very responsive, no need to carry my iPhone around with me.

**Comment by dmckillican** [comment]
(ps. with dimming, I really cannot think of anything else 👍). Your plugin is far superior to anything else.

**Comment by rainlake** [comment]
Good, I give up Osram skill long time ago
